server:
  port: 8081


name: abc
# 对象
person:
  name: ${name}    #zhangshang  &{name} 参数引用
  age: 20
  address:
    - beijing
    - shanghai
# 对象行内写法
person2: {name: zhangshang,age: 20}

# 数组
address:
  - beijing
  - shanghai
# 数组行内写法
address2: [beijing,shanghai]

#纯量
msg1: 'hello \n world'  #不会识别转义字符，原样输出
msg2: "hello \n world"  #会识别转义字符，原样输出